# Generated by Django 5.1.3 on 2024-11-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('location_description', models.TextField()),
                ('location_image', models.ImageField(upload_to='locations')),
            ],
        ),
    ]
