# Generated by Django 5.1.3 on 2024-11-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
